#!/bin/bash -e

while read -r line; do
    if [[ $line != */vmlinuz ]]; then
        # triggers when it's a change to usr/lib/systemd/*
        continue
    fi

    if ! read -r pkgbase > /dev/null 2>&1 < "${line%/vmlinuz}/pkgbase"; then
        # if the kernel has no pkgbase, we skip it
        continue
    fi

    version=$(basename "${line%/vmlinuz}")

    kernel-install $1 "${version}" "${line}"
done
